Map<String, int> itemsMap = {
  "Basmati Rice": 60,
  "Sona masoori Rice": 50,
  "Plain Rice": 45,
  "Toor Dal": 70,
  "Moong Dal": 104,
  "Udit Dal": 65,
  "Chana Dal": 60,
  "Peanut": 83,
  "Dove": 40,
  "Santoor": 25,
  "Mysore Sandal": 30,
  "Pears": 50,
  "Head & Shoulders": 80,
  "Clinic Plus": 75,
  "Johnsonsbaby": 100,
  "Hide & Seek": 30,
  "Oreo": 30,
  "Bourbon": 10,
  "Colgate Paste": 30,
  "Close up Paste": 25,
  "Patanjali Paste": 40,
};
